---
title: "billionaires"
author: "Subodh"
date: "9/29/2021"
output: html_document
---

```{r}
library(rvest)
library(tidyverse)
setwd("~/Desktop/Pet Analysis/Misc")
```

```{r}
url <- read_html("https://en.wikipedia.org/wiki/The_World%27s_Billionaires")
df <- url %>% html_table()
```

```{r}
Y2021 <- df[[3]]
Y2021$Year <- 2021
Y2020 <- df[[4]]
Y2020$Year <- 2020
Y2019 <- df[[5]]
Y2019$Year <- 2019
Y2018 <- df[[6]]
Y2018$Year <- 2018
Y2017 <- df[[7]]
Y2017$Year <- 2017
Y2016 <- df[[8]]
Y2016$Year <- 2016
Y2015 <- df[[9]]
Y2015$Year <- 2015
Y2014 <- df[[10]]
Y2014$Year <- 2014
Y2013 <- df[[11]]
Y2013$Year <- 2013
Y2012 <- df[[12]]
Y2012$Year <- 2012
Y2011 <- df[[13]]
Y2011$Year <- 2011
Y2010 <- df[[14]]
Y2010$Year <- 2010
Y2009 <- df[[15]]
Y2009$Year <- 2009
Y2008 <- df[[16]]
Y2008$Year <- 2008
Y2007 <- df[[17]]
Y2007$Year <- 2007
Y2006 <- df[[18]]
Y2006$Year <- 2006
Y2005 <- df[[19]]
Y2005$Year <- 2005
Y2004 <- df[[20]]
Y2004$Year <- 2004
Y2003 <- df[[21]]
Y2003$Year <- 2003
Y2002 <- df[[22]]
Y2002$Year <- 2002
Y2001 <- df[[23]]
Y2001$Year <- 2001
Y2000 <- df[[24]]
Y2000$Year <- 2000

billionaires <- rbind(Y2021,Y2020,Y2019,Y2018,Y2017,Y2016,Y2015,Y2014,Y2013,Y2012,Y2011,Y2010,Y2009,Y2008,Y2007,Y2006,Y2005,Y2004,Y2003,Y2003,Y2002,Y2001,Y2000)
billionaires$Wealth <- str_extract(billionaires$`Net worth (USD)`,"\\d+")
billionaires$Wealth <- as.numeric(billionaires$Wealth)
billionaires

billionaires%>%  ggplot(aes(reorder(Name,-Wealth), Wealth, fill=Nationality))+
  geom_col()+
  
  facet_wrap(Year~., scales = c("free_x"))+
   theme(axis.text.x = element_text(angle=90))

write.csv(billionaires,"billionaires.csv")
  ?fct_lump
```

