---
title: "COVID"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    
---

```{r setup, include=TRUE}
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(plotly)
library(reshape2)
library(directlabels)
library(scales)
library("ggrepel")

library(TTR)
library(DT)
library(ggplot2)
library(gganimate)
library(highcharter)


df <- read.csv("https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/jhu/full_data.csv")
location <- read.csv("https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/01-01-2021.csv")
df[is.na(df)]=0
df$Death_Moving_Average<-SMA(df$new_deaths, n=7)
df$Death_Moving_Average <- round(df$Death_Moving_Average, digits = 2)

df$Case_Moving_Average<-SMA(df$new_case, n=7)
df$Case_Moving_Average <- round(df$Case_Moving_Average, digits = 2)
df$date <- ymd(df$date)



```
# NEpal

## Column {data-width=1000}


### Chart A

```{r}

d <- df %>% filter(location %in% c("India","Nepal")) %>%
  group_by(location,date) %>% 
  ggplot(aes(x=date, color=location))+
  geom_line(aes(y=total_cases), lwd=1)+
  #geom_line(aes(y=new_deaths),linetype="dotted", lwd=1)+
  scale_y_continuous(label=comma)+
  scale_y_continuous(trans ="log10",breaks  =c(0,10,100,1000,10000,100000,1000000,10000000,100000000),label=comma)+
  labs(x="",
       y="Total Cases",
       title="COVID Cases in Nepal and India",
       caption="Source: John Hopkins University \n Note: Data is from Jan 25, 2020 through May 2021")+
      theme(axis.text.x = element_text(angle=90,size = 10),
          axis.text.y = element_text(size=10),
        
          axis.title.y = element_text(size=20, face="bold"),
        axis.ticks.x=element_blank(),
       plot.background=element_rect(fill="white"),
       panel.background=element_rect(fill="white"),
      #panel.grid.major.y = element_blank(),
      panel.grid.major.x = element_blank(),
      #panel.grid.minor.y = element_blank(),
       panel.grid.minor.x = element_blank(),
       legend.position = "right",
      legend.title = element_blank())+
  
   scale_x_date(date_breaks = "months" , date_labels = "%b-%y")

ggsave("COVID.png")
  

  
 
d
```

## Column {data-width=700}

### Chart B

```{r}
e <- df %>% filter(location %in% c("India","United States", "Brazil")) %>%
  group_by(location,date) %>% 
  ggplot(aes(x=date, color=location))+
  geom_line(aes(y=total_cases), lwd=1)+
  #geom_line(aes(y=new_deaths),linetype="dotted", lwd=1)+
  scale_y_continuous(label=comma)+
  #scale_y_continuous(trans ="log10",breaks  =c(0,10,100,1000,10000,100000,1000000,10000000,100000000),label=comma)+
  labs(x="",
       y="Total Cases",
       title="COVID Cases",
       caption="Source: John Hopkins University \n Note: Data is from Jan 25, 2020 through May, 2021")+
      theme(axis.text.x = element_text(angle=90,size = 10, face="bold", colour = "red"),
          axis.text.y = element_text(size=10, face = "bold", color = "blue"),
          axis.title.y = element_text(size = 20, face = "bold"),
        axis.ticks.x=element_blank(),
       plot.background=element_rect(fill="white"),
       panel.background=element_rect(fill="white"),
      #panel.grid.major.y = element_blank(),
      panel.grid.major.x = element_blank(),
      #panel.grid.minor.y = element_blank(),
       panel.grid.minor.x = element_blank(),
       legend.position = "right",
      legend.title = element_blank())+
  
   scale_x_date(date_breaks = "months" , date_labels = "%b-%y")

#ggsave("COVID.png")
  

  
 
e
```

### Chart C

```{r}
ef <-df %>% 
  filter(location=="India") %>% 
  ggplot()+
  geom_col(aes(x=date,y=new_deaths),color="black",fill="blue")+
  geom_line(aes(x=date,y=Death_Moving_Average), lwd=1, color="red")+
  scale_y_continuous(sec.axis = sec_axis(~./1, name = "Moving Average deaths"))+
  scale_x_date(date_breaks = "months" , date_labels = "%b-%y")+
  theme(axis.text.x = element_text(angle=90),
        legend.title = element_blank())
ggplotly(ef)
```


# SS

## column {data-width=500}
