---
title: "Nepal"
author: "Subodh"
date: "4/20/2021"
output: html_document
---


```{r}
setwd("~/Desktop/Pet Analysis/Misc/")
library(tidyverse)
library(plotly)
library(zoo)
library(lubridate)
```

```{r}
df <- read.csv("Number of Nepalese people going abroad,2000-2013.csv")
df$Month<-substr(df$Month,1,3)
df$date <- paste(df$Year.AD,df$Month, "1", sep="-")
df$date <- ymd(df$date)
df <- mutate(df, Cumilative=cumsum(Nepalese.going.aboard.by.month))

d<-df %>% group_by(Year.AD) %>%
  summarise(Total=sum(Nepalese.going.aboard.by.month))%>% 
  ggplot(aes(Year.AD,Total/1000))+
  geom_line(lwd=1, color="red")+
  scale_x_continuous(breaks = seq(2000,2013,3))+
  labs(x="Year",
       y="Cumulative Migration",
       title = "Nepal Migration Rate (in 1000s)",
       caption = "Source: NACUBO")+
  
  theme(plot.background=element_blank(),
        panel.background = element_rect(fill="grey"),
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank(),
        plot.title= element_text(hjust = 0.5, face = "bold"),
        axis.ticks.x = element_blank(),
  
  legend.position="none")
ggplotly(d)
df
```

```{r}
df %>% group_by(Year.AD) %>%
  summarise(Total=sum(Nepalese.going.aboard.by.month))%>% 
  ggplot(aes(Year.AD,Total/1000))+
  geom_bar(stat = "identity")+
  scale_x_continuous(breaks = seq(2000,2013,3))+
  labs(x="Year",
       y="Cumulative Migration",
       title = "Nepal Migration Rate (in 1000s)",
       caption = "Source: NACUBO")+
  
  theme(plot.background=element_blank(),
        panel.background = element_rect(fill="black"),
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank(),
        plot.title= element_text(hjust = 0.5, face = "bold"),
        axis.ticks.x = element_blank(),
  
  legend.position="none")
```


```{r}
year <- df %>% 
  group_by(Year.AD) %>% 
  summarise(Total = sum(Nepalese.going.aboard.by.month)) %>% 
  mutate(Rollover=cumsum(Total)) %>% 
  mutate(Rollover=round(Rollover/10000, digits = 0))
year


```

```{r}
 ggplot(year,aes(x=Year.AD,Rollover))+
  geom_bar(stat="identity",fill="dark red",color="black")+
  scale_y_continuous(breaks = seq(0,7000, by=500))+
  scale_x_continuous(breaks = seq(2000,2013, by=1))+
  coord_flip()+
  labs(x="Year",
       y="Cumulative Migration",
       title = "Nepal Migration Rate",
       caption = "Source: NACUBO")+
  
  theme(plot.background=element_blank(),
        panel.background = element_rect(fill="white"),
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
  
  legend.position="none")+
  geom_text(aes(label=Rollover, size=.005),hjust=-0.010)
#ggplotly(e)
```







```{r}
df %>% 
ggplot(aes(Nepalese.going.aboard.by.month))+
  geom_density()+
  facet_grid(year~)
```

